### ISSUE TITLE
help with instalation of teh EcoNet300

### ISSUE THREAD

**Issue by Maystero14** [pblxptr/ecoNET-300-Home-Assistant-Integration#16]
Cześć. Próbuje zainstalować https://github.com/pblxptr/ecoNET-300-Home-Assistant-Integration
wykonałem połowę instrukcji i sie zakopałem. Dalsza część jest nie jasna dla mnie. Czy mogę cie prosić o pomoc?

**Comment by pblxptr** [comment]
[ENG] in general please stick to English as this project may be used widely by non native speakers.

[PL] w czym właściwie jest problem? Na czym się zatrzymałeś? Najważniejsza część to instalacja customowego repo w HACS, później dodajesz integrację z poziomu GUI tak jak każda inna

**Comment by Maystero14** [comment]
Hello.
at the moment I have did:
with [this guide](https://hacs.xyz/docs/faq/custom_repositories) I did instalation of: https://github.com/pblxptr/ecoNET-300-Home-Assistant-Integration

whats now?
```
<config directory>/
|-- custom_components/
|   |-- econet300/
|       |-- [...]
``` 

I don't understand. Whare? Whats?

In teh  HACS I have:
![Zrzut ekranu 2023-03-18 182258](https://user-images.githubusercontent.com/124868352/226122903-a18c79a4-ea84-43c4-ad38-abd924402548.jpg)

**Comment by pblxptr** [comment]
> Hello. at the moment I have did: with [this guide](https://hacs.xyz/docs/faq/custom_repositories) I did instalation of: https://github.com/pblxptr/ecoNET-300-Home-Assistant-Integration
> 
> whats now?
> 
> ```
> <config directory>/
> |-- custom_components/
> |   |-- econet300/
> |       |-- [...]
> ```
> 
> I don't understand. Whare? Whats?
> 
> In teh HACS I have: ![Zrzut ekranu 2023-03-18 182258](https://user-images.githubusercontent.com/124868352/226122903-a18c79a4-ea84-43c4-ad38-abd924402548.jpg)

You have to either install it manually or install it through HACS. I assume that you've chosen HACS. Then when the installation process is finished, you should configure the integration. At this point, you also have two options described here: https://github.com/pblxptr/ecoNET-300-Home-Assistant-Integration#configuration

You can click 'Add integration' button and follow the steps, or configure it manually - just expand the drop-down list "Manual Configuration Steps" and you will see how you should proceed with this. There are also some screenshots. Let me know once you've managed to do this or stumbled upon some other problems.

**Comment by Maystero14** [comment]
Thank you for help. Made as suggested:
![Zrzut ekranu 2023-03-18 203301](https://user-images.githubusercontent.com/124868352/226133599-72051818-65b3-40a4-8fa9-c66a8661e986.jpg)

When I clik "seting"
![Zrzut ekranu 2023-03-18 203440](https://user-images.githubusercontent.com/124868352/226133652-b052d320-26de-460b-a7fa-52b1918c2242.jpg)
Whats is next step?

**Comment by Maystero14** [comment]
I am asking for help again.

**Comment by pblxptr** [comment]
> I am asking for help again.

To be honest I don't know how to help you. I installed it today again and I had no problems. Also I haven't heard any complains regarding instalation proces from other users. Please have a look at the readme again and go step by step once again

**Comment by Maystero14** [comment]
OK. I did procedure again And now is working. 
![Zrzut ekranu 2023-03-22 211332](https://user-images.githubusercontent.com/124868352/227027496-581340ef-0bbe-48b9-b825-42836e08531c.jpg)

But I know what I did wrong.

I have 2x devices:
one: 192.168.x.133 - this working
second: 192.168.x.134 - this not working
The first device is name: ecoMAXX800R
The second device is name: ecoSOL 301

Both are connected by EcoNet24

**Comment by pblxptr** [comment]
> OK. I did procedure again And now is working. ![Zrzut ekranu 2023-03-22 211332](https://user-images.githubusercontent.com/124868352/227027496-581340ef-0bbe-48b9-b825-42836e08531c.jpg)
> 
> But I know what I did wrong.
> 
> I have 2x devices: one: 192.168.x.133 - this working second: 192.168.x.134 - this not working The first device is name: ecoMAXX800R The second device is name: ecoSOL 301
> 
> Both are connected by EcoNet24

In general, this integration is intended to work with boiler controllers connected through ecoNET300.
So it will work in a scenario where you have a boiler controller e.g. ecoMAX920P1 (in my case), which is connected to ecoNET300 which severs as a gateway to the Internet. 

From what I see, the ecoSOL module is something completely different, which provides an Internet connection on its own.

**Comment by pblxptr** [comment]
I'm closing this issue as it seems that everything has been clarified.
