### ISSUE TITLE
Future. Possibility to turn off the boiler

### ISSUE THREAD

**Issue by jontofront** [pblxptr/ecoNET-300-Home-Assistant-Integration#4]
Hi,
I figure out that we can on and of boiler by these commands:
**Boiler OFF**
http://x.x.x.x/econet/newParam?newParamName=BOILER_CONTROL&newParamValue=0
![image](https://user-images.githubusercontent.com/37038426/210387087-7440a541-f7b4-4e3d-91aa-b1fc856cb42f.png)
![image](https://user-images.githubusercontent.com/37038426/210387144-3c9ba367-2e32-4271-9b09-2800b6b0eec5.png)

**Boiler ON**
http://x.x.x.x/econet/newParam?newParamName=BOILER_CONTROL&newParamValue=1
![image](https://user-images.githubusercontent.com/37038426/210387290-c5ee5ee4-ede1-411f-b484-909628128f2a.png)

**Comment by pblxptr** [comment]
> Hi, I figure out that we can on and of boiler by these commands: **Boiler OFF** http://x.x.x.x/econet/newParam?newParamName=BOILER_CONTROL&newParamValue=0 ![image](https://user-images.githubusercontent.com/37038426/210387087-7440a541-f7b4-4e3d-91aa-b1fc856cb42f.png) ![image](https://user-images.githubusercontent.com/37038426/210387144-3c9ba367-2e32-4271-9b09-2800b6b0eec5.png)
> 
> **Boiler ON** http://x.x.x.x/econet/newParam?newParamName=BOILER_CONTROL&newParamValue=1 ![image](https://user-images.githubusercontent.com/37038426/210387290-c5ee5ee4-ede1-411f-b484-909628128f2a.png)

What about boiler status? Does any parameter accessible through regParams change when you switch off/on?

**Comment by jontofront** [comment]
If you mean about boiler operation mode status:
Key: mode

```
OFF = 0
FANNING = 1
FIRE UP= 2
WORKING = 3
SUPERVISION = 4
FIVE = 5 
SIX = 6
BURNING_OFF = 7
ALERT = 8
```

**Comment by pblxptr** [comment]
I did small investigation and it seems that it will be a bit trickier. For example my EcoNet once module returned mode equal to 14 which is missing on your list. Maybe it differes between fw version or something. Anyways it requires further investigation.

**Comment by jontofront** [comment]
What is [Plum Sp. z o.o.](https://www.plum.pl/) and Module Econet software version you have?

**Comment by pblxptr** [comment]
> What is [Plum Sp. z o.o.](https://www.plum.pl/) and Module Econet software version you have?

ecosrvSoftVer: 3.2.3819
lbModuleAVerCurr: 12.11.49
lbPanelModuleVerCurr: 12.10.39
lbEcoSTERModuleVer1Curr: 1.14.73

**Comment by denpamusic** [comment]
You might want to take a look at frontend api client (controller.js) from ecoNET firmware 3.2.3678, that I unpacked and run through beautifier:
https://gist.github.com/denpamusic/6cbe2af44ee02eb22a001b7543438928

It's not a documentation per se, but at least lists all ecoNET endpoints in neat form😉

**Comment by pblxptr** [comment]
> You might want to take a look at frontend api client (controller.js) from ecoNET firmware 3.2.3678, that I unpacked and run through beautifier: https://gist.github.com/denpamusic/6cbe2af44ee02eb22a001b7543438928
> 
> It's not a documentation per se, but at least it lists all ecoNET endpoints in neat formwink

Thanks this will definitely help!

**Comment by petr-nov** [comment]
Hi,
good job, thanks for that. 
However, the temperature values for Mixer1 and Mixer 2 have not been available for some time. After the last update, they were also separated into a separate device.
![obrazek](https://user-images.githubusercontent.com/110833622/213159343-72376bfd-5a57-4df1-95da-10c06793ce88.png)

**Comment by pblxptr** [comment]
@jontofront 

Sorry I have to clarify a few things. First, I said that "Set water temperature" and "Set boiler temperature" are available on the master branch - that's not true. They are on a separate branch and I will probably push these changes today. On the master branch, you should already have changes related to the device info - ecoNET300 firmware version. 

As for Mixer devices - I guess that you have used my changes from 'dev' branch where I was checking a few things regarding mixers. This branch is no longer available as well as mixer devices are not available on the master. 

Let's do this in the following steps: 
1) First, make sure that you have the newest version from master (there should be support for fw version). The best would be if you could reinstall the integration once again

2) If everything works as expected in the above step, I will push changes related to "Boiler set temperature" and "Water set temperature", these are settable parameters so it would be good if you could check if they work.  They will be so far limited to what I've said before - which is, that the target value will be possible to set only to the current value equal to -1 or +1.

3) If everything works as expected in the above step, I will prepare changes related to mixer devices.

Are you fine with this?

Also, I recommend not to relay on changes that are available on other branches that 'master' or tags, because e.g. on 'dev' branch I do some stuff, I test a few things, then merge them or don't, so other branches should be considered as unstable.

**Comment by pblxptr** [comment]
@jontofront Thanks! Yes, these logs are fine, they just indicate that an entity will not be added because data for this entity is not available so there is no use in creating it.

I will create a new tag.

**Comment by jontofront** [comment]
> I did small investigation and it seems that it will be a bit trickier. For example my EcoNet once module returned mode equal to 14 which is missing on your list. Maybe it differes between fw version or something. Anyways it requires further investigation.

Today a got error :) so Status 8 is ок :)

![image](https://user-images.githubusercontent.com/37038426/213505474-5ed303bc-204f-4f5c-98e0-b84fa39b17a7.png)


![image](https://user-images.githubusercontent.com/37038426/213505295-70d19a45-2a02-4c29-96ef-1872d93d1359.png)

**Comment by jontofront** [comment]
@pblxptr can you check please http://ecoNET_Local_IP/econet/rmParamsEnums?
The are value names:
![image](https://user-images.githubusercontent.com/37038426/215019216-69f5710b-6f46-4a02-934c-a510330ff393.png)

`
    {
      "values": [
        "TURNED OFF",
        "FIRE UP",
        "STABILIZATION",
        "OPERATION",
        "SUPERVISION",
        "BURNING OFF",
        "STOP",
        "R.P.OUT",
        "MANUAL",
        "ALARM",
        "UNSEALING",
        "CHIMNEY",
        "ACTIVACTION",
        "NO TRANSMISSION"
      ],
      "first": 0

`

**Comment by jontofront** [comment]
@pblxptr sorry for the ping :) but maybe you can check link with Boiler status enums?

**Comment by pblxptr** [comment]
@jontofront I remember about this, but I've been working on a different project simultaneously and I have to finish it. Fortunately, we should finalize it in two weeks (I hope) so I will get back to this.

**Comment by Marek7923** [comment]
Witam, Panie Patryku,
Udało mi się odrobine zmodyfikować plik czujnikami, jednak do wypełni szczęścia brakuje zwrotu informacji o trybie pracy kotła.
Zmienna mode zwraca wartość numeryczną, jednak jako laik który z Home Assistant pracuje niespełna 2 tygodnie nie umiem tego ugryźć.  
Wiem że jest Pan zajętym człowiekiem, ale bardzo prosił bym o pomoc.   

![Zrzut ekranu 2023-02-25 214421](https://user-images.githubusercontent.com/125127838/221378847-7eeaeb82-1f31-4394-8e8d-c035f7549b49.jpg)

**Comment by Marek7923** [comment]
Ostatnie odczyty z bufora to moja dokładka z 4 czujnikami DS18B20 odczytywane z ESP8266

**Comment by bigoblins** [comment]
> Witam, Panie Patryku, Udało mi się odrobine zmodyfikować plik czujnikami, jednak do wypełni szczęścia brakuje zwrotu informacji o trybie pracy kotła. Zmienna mode zwraca wartość numeryczną, jednak jako laik który z Home Assistant pracuje niespełna 2 tygodnie nie umiem tego ugryźć. Wiem że jest Pan zajętym człowiekiem, ale bardzo prosił bym o pomoc. Ostatnie odczyty z bufora to moja dokładka z 4 czujnikami DS18B20 odczytywane z ESP8266
> 
> ![Zrzut ekranu 2023-02-25 214421](https://user-images.githubusercontent.com/125127838/221378847-7eeaeb82-1f31-4394-8e8d-c035f7549b49.jpg)

add configuration.yaml code:

sensor:
  - platform: template
    sensors:
      name_kotel_status:
        value_template: >
          {% if is_state('sensor.mode', "0") %}BЫКЛЮЧEHO
          {% elif is_state('sensor.mode', "1") %}hz 1
          {% elif is_state('sensor.mode', "2") %}Розжиг
          {% elif is_state('sensor.mode', "3") %}РАБОТА
          {% elif is_state('sensor.mode', "4") %}Надзор
          {% elif is_state('sensor.mode', "5") %}Простой
          {% elif is_state('sensor.mode', "6") %}hz 6
          {% elif is_state('sensor.mode', "7") %}Гашение
          {% elif is_state('sensor.mode', "8") %}ТРЕВОГА
          {% elif is_state('sensor.mode', "9") %}ОЧИСТКА
          {% elif is_state('sensor.mode', "10") %}hz 8
          {% elif is_state('sensor.mode', "11") %}Старт
          {% elif is_state('sensor.mode', "12") %}Стабилизация
          {% elif is_state('sensor.mode', "13") %}hz 13
          {% elif is_state('sensor.mode', "14") %}ТЕСТ пламени
          {% else %}Unavailable
          {% endif %}

add page:
type: entity
entity: sensor.name_kotel_status

![image](https://user-images.githubusercontent.com/77337894/223724117-86413318-263e-4260-9e47-dd1ebe63d57b.png)

**Comment by bigoblins** [comment]
please exemples code related to "Boiler set temperature" and "Water set temperature" -1 +1?

**Comment by petr-nov** [comment]
> > ![Zrzut ekranu 2023-02-25 214421](https://user-images.githubusercontent.com/125127838/221378847-7eeaeb82-1f31-4394-8e8d-c035f7549b49.jpg)
> 
> add configuration.yaml code:
> 
> sensor:
> 
>     * platform: template
>       sensors:
>       name_kotel_status:
>       value_template: >
>       {% if is_state('sensor.mode', "0") %}BЫКЛЮЧEHO
>       {% elif is_state('sensor.mode', "1") %}hz 1
>       {% elif is_state('sensor.mode', "2") %}Розжиг
>       {% elif is_state('sensor.mode', "3") %}РАБОТА
>       {% elif is_state('sensor.mode', "4") %}Надзор
>       {% elif is_state('sensor.mode', "5") %}Простой
>       {% elif is_state('sensor.mode', "6") %}hz 6
>       {% elif is_state('sensor.mode', "7") %}Гашение
>       {% elif is_state('sensor.mode', "8") %}ТРЕВОГА
>       {% elif is_state('sensor.mode', "9") %}ОЧИСТКА
>       {% elif is_state('sensor.mode', "10") %}hz 8
>       {% elif is_state('sensor.mode', "11") %}Старт
>       {% elif is_state('sensor.mode', "12") %}Стабилизация
>       {% elif is_state('sensor.mode', "13") %}hz 13
>       {% elif is_state('sensor.mode', "14") %}ТЕСТ пламени
>       {% else %}Unavailable
>       {% endif %}
> 
> 
> add page: type: entity entity: sensor.name_kotel_status
> 
> ![image](https://user-images.githubusercontent.com/77337894/223724117-86413318-263e-4260-9e47-dd1ebe63d57b.png)

How did you manage to add boiler schema to HA?

**Comment by petr-nov** [comment]
Excellent!

**Comment by jontofront** [comment]
> took a screenshot, added it as a ''type: picture-elements' and then placed the sensors
> 
> ![image](https://user-images.githubusercontent.com/77337894/223769772-84d5d98a-f709-4446-a7b8-98e545313de8.png)

Can you share code in txt message?

**Comment by bigoblins** [comment]
here is the code,
I added some sensors that weren't there: 

`type: picture-elements
title: ''
style: |
  ha-card { width: 960px !important;
          }
elements:
  - type: state-label
    entity: sensor.fireplace_temperature
    title: Температура котла
    style:
      top: 56.4%
      left: 40%
      color: '#fff'
      font-size: 11px
  - type: state-label
    entity: sensor.boiler_set_temp
    title: Заданная температура котла
    style:
      top: 60.6%
      left: 40%
      color: '#fff'
      font-size: 11px
  - type: state-label
    entity: sensor.exhaust_temperature
    title: Температура продуктов сгорания
    style:
      top: 38.6%
      left: 37%
      color: '#fff'
      font-size: 11px
  - type: state-label
    entity: sensor.water_back_temperature
    title: Температура возврата
    style:
      top: 92.6%
      left: 39.6%
      color: '#fff'
      font-size: 11px
  - type: state-label
    entity: sensor.water_temperature
    title: Температура ГВС
    style:
      top: 47.4%
      left: 86.6%
      color: '#fff'
      font-size: 11px
  - type: state-label
    entity: sensor.cwu_set_temp
    title: Заданная температура ГВС
    style:
      top: 51.6%
      left: 86%
      color: '#fff'
      font-size: 11px
  - type: state-label
    entity: sensor.outside_temperature
    title: Внешняя температура
    style:
      top: 5.8%
      left: 33%
      color: '#fff'
      font-size: 11px
  - type: state-label
    entity: sensor.ecoster_set_temp_1
    title: Заданная температура 1
    style:
      top: 5.2%
      left: 46.5%
      color: '#fff'
      font-size: 11px
  - type: state-label
    entity: sensor.ecoster_temperature_1
    title: Температура первого этажа
    style:
      top: 5.2%
      left: 59%
      color: '#fff'
      font-size: 11px
  - type: state-label
    entity: sensor.ecoster_set_temp_2
    title: Заданная температура 2
    style:
      top: 5.3%
      left: 69.4%
      color: '#fff'
      font-size: 11px
  - type: state-label
    entity: sensor.mixer_ecoster_temperature_2
    title: Температура второго этажа
    style:
      top: 5.2%
      left: 82.5%
      color: '#fff'
      font-size: 11px
  - type: state-label
    entity: sensor.mixer_set_temp_1
    title: Заданная темп. смесителя 1
    style:
      top: 31%
      left: 58.5%
      color: '#fff'
      font-size: 11px
  - type: state-label
    entity: sensor.mixertemp_1
    title: Температура смесителя 1
    style:
      top: 26.8%
      left: 58.7%
      color: '#fff'
      font-size: 11px
  - type: state-label
    entity: sensor.mixer_set_temp_2
    title: Заданная темп. смесителя 2
    style:
      top: 31%
      left: 71.5%
      color: '#fff'
      font-size: 11px
  - type: state-label
    entity: sensor.mixer_temperature_2
    title: Температура смесителя 2
    style:
      top: 26.8%
      left: 71.7%
      color: '#fff'
      font-size: 11px
  - type: state-label
    entity: sensor.boiler_output
    title: Мощность котла
    style:
      top: 33%
      left: 17%
      color: '#000'
      font-size: 15px
  - type: state-label
    entity: sensor.name_kotel_status
    title: Режим работы
    style:
      top: 33%
      left: 6%
      color: '#000'
      font-size: 15px
  - type: state-label
    entity: sensor.fuel_level
    title: Уровень топлива
    style:
      top: 62%
      left: 6%
      color: '#000'
      font-size: 15px
  - type: state-label
    entity: sensor.fan_power
    title: Мощность наддува
    style:
      top: 92%
      left: 6%
      color: '#000'
      font-size: 15px
  - type: image
    title: Насос котла
    entity: binary_sensor.co_pump
    image: /local/images/on-nasos.png
    state_image:
      'off': /local/images/off-nasos.png
    style:
      top: 83.3%
      left: 43%
      width: 3%
  - type: image
    title: Насос ГВС
    entity: binary_sensor.water_pump
    image: /local/images/on-nasos.png
    state_image:
      'off': /local/images/off-nasos.png
    style:
      top: 61%
      left: 81%
      width: 3%
      transform: rotate(0.5turn)
  - type: image
    title: Циркуляционный насос ГВС
    entity: binary_sensor.circulation_pump
    image: /local/images/on-nasos.png
    state_image:
      'off': /local/images/off-nasos.png
    style:
      top: 47%
      left: 93%
      width: 3%
      transform: rotate(0.25turn)
  - type: image
    title: Насос первого этажа
    entity: binary_sensor.mixerpumpworks1_pump
    image: /local/images/on-nasos.png
    state_image:
      'off': /local/images/off-nasos.png
    style:
      top: 34%
      left: 62.1%
      width: 3%
      transform: rotate(0.25turn)
  - type: image
    title: Насос второго этажа
    entity: binary_sensor.mixer_pump_2
    image: /local/images/on-nasos.png
    state_image:
      'off': /local/images/off-nasos.png
    style:
      top: 34%
      left: 75%
      width: 3%
      transform: rotate(0.25turn)
image: /local/images/hema_otoplrnija-1.png
`

**Comment by bigoblins** [comment]
image:
![hema_otoplrnija-1](https://user-images.githubusercontent.com/77337894/224467336-bd71b934-c3e5-4bb0-b62d-53e6b06c8ddb.png)
