### ISSUE TITLE
Sensors. get boilerPower sensor and boiler operation mode

### ISSUE THREAD

**Issue by jontofront** [pblxptr/ecoNET-300-Home-Assistant-Integration#5]
From /econet/regParams? I figure out these boiler states

Key: `mode`

Constants means:
```
    OFF = 0
    FANNING = 1
    FIRE UP= 2
    WORKING = 3
    SUPERVISION = 4
    BURNING_OFF = 7
    ALERT = 8
```

Can you add please Boiler output sensor
```
key="boilerPower",
name="Boiler output", 
icon="mdi:gauge",
native_unit_of_measurement=PERCENTAGE,
```

**Comment by pblxptr** [comment]
@jontofront As for boilerPower please check #7 and let me know if it's ok

**Comment by jontofront** [comment]
Thanks I see now boiler output. There are no errors in logs
![image](https://user-images.githubusercontent.com/37038426/210559771-888d669f-890c-4f90-b8f3-9d992c2eb306.png)
